from graphs2 import *

if __name__ == "__main__":
    # Testing for Hamiltonian Graph
    g = Graph(False)
    g != None
    g.addVertex("1")
    g.addVertex("2")
    g.addVertex("3")
    g.addVertex("4")
    g.addVertex("5")
    g.addVertex("6")
    g.addVertex("7")
    g.addVertex("8")
    g.addEdge("1", "2")
    g.addEdge("1", "4")
    g.addEdge("1", "5")
    g.addEdge("2", "3")
    g.addEdge("2", "5")
    g.addEdge("2", "6")
    g.addEdge("3", "4")
    g.addEdge("3", "7")
    g.addEdge("4", "6")
    g.addEdge("4", "7")
    g.addEdge("5", "8")
    g.addEdge("6", "8")
    g.addEdge("7", "8")
    graph = prepareGraphForHamilton(g.createAdjacencyList())
    result = hamiltonCycle(list(graph))
    print("Hamilton cycle :", result)
    drawCircularGraph(g, 4, "Hamilton1.png")

    # Testing for Non-Hamiltonian graph
    g2 = Graph(False)
    g2 != None
    g2.addVertex("1")
    g2.addVertex("2")
    g2.addVertex("3")
    g2.addVertex("4")
    g2.addVertex("5")
    g2.addEdge("1", "2")
    g2.addEdge("2", "3")
    g2.addEdge("3", "4")
    g2.addEdge("4", "1")
    g2.addEdge("2", "4")
    g2.addEdge("2", "5")
    g2.addEdge("4", "5")
    drawCircularGraph(g2, 4, "Hamilton2.png")
    graph2 = prepareGraphForHamilton(g2.createAdjacencyList())
    result2 = hamiltonCycle(graph2)
    print("Hamilton cycle :", result2)
